[package]
name = "spark-corefw-rs"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "spark-corefw-rs"
path = "src/main.rs"

[dependencies]
embassy-stm32 = { version = "0.2", features = [
    "stm32h723zg",
    "time-driver-tim5",
    "time",
    "exti",
    "unstable-pac",
] }
embassy-executor = { version = "0.7", features = [
    "arch-cortex-m",
    "executor-thread",
    "task-arena-size-8192",
] }
embassy-time = { version = "0.4", features = ["tick-hz-1_000_000"] }
embassy-futures = "0.1"
embassy-sync = "0.7"
cortex-m = { version = "0.7", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7"
panic-halt = "1.0"
heapless = "0.8"

[profile.release]
debug = 2
opt-level = "s"
lto = "thin"
codegen-units = 1
